import fs from 'node:fs';
const edit=(p,fn)=>fs.writeFileSync(p,fn(fs.readFileSync(p,'utf8')));
edit('src/world/generation/WorldGenerator.ts',s=>s.replace('            pois,','            pois,\n            version,').replace('          pois,\n        ),','          pois,\n          version,\n        ),'));
edit('src/ui/PanelController.ts',s=>s.replace("root.querySelectorAll<HTMLElement>('button:not(:disabled),input,select,[tabindex=\"0\"]')","root.querySelectorAll<HTMLElement>('.panel-frame button:not(:disabled),.panel-frame input,.panel-frame select,.panel-frame [tabindex=\"0\"]')").replace("this.root.querySelector<HTMLElement>('button,input')","this.root.querySelector<HTMLElement>('.panel-frame button,.panel-frame input')"));
edit('src/ui/UI.ts',s=>s.replace("showMenu(){this.menuMode=true;","showMenu(){this.atlas?.destroy();this.tree?.destroy();this.root.classList.remove('panel-open');this.menuMode=true;").replace("showGame(){this.menuMode=false;","showGame(){this.root.classList.remove('panel-open');this.menuMode=false;").replace("case'item-select':this.selectedItem=id;this.syncPanel();return;","case'item-select':{this.selectedItem=id;this.root.querySelectorAll<HTMLElement>('.bag-grid [data-item]').forEach(b=>b.classList.toggle('chosen',b.dataset.item===id));const item=e?.run.inventory.find(i=>i.id===id),footer=this.root.querySelector('.inventory-selection');if(item&&footer)footer.innerHTML='<b>'+esc(item.name)+'</b>'+gameButton('Equipar','equip',id)+'<small>Duplo clique também equipa</small>';return;}"));
edit('src/ui/SkillTreeView.ts',s=>s.replace("i<4||c.passives[i-4]","i<4||c.passives.includes(cls.passives[i-4])"));
edit('src/rendering/EntityRenderer.ts',s=>s.replace('import { rarityNames','import { balance } from "../data/balance";\nimport { rarityNames').replace('sprite.setScale(hero ? 1 : entity.elite ? 1.2 : 1);','sprite.setScale(hero ? balance.characterScale : entity.elite ? 1.28 : 1.08);\n      if(!dead && entity.attackTime>0 && !moving) sprite.rotation=Math.sin(time*.04)*.035;').replace('if (entity.statuses.some((s) => s.id === "burn"))','if(this.e.effects.some(f=>f.kind==="hit"&&f.remaining>f.duration-.09&&Math.hypot(f.x-entity.x,f.y-entity.y)<.3)) sprite.setTintFill(0xe5e2bc);\n      else if (entity.statuses.some((s) => s.id === "burn"))').replace('entity.id === this.e.selected.target','(entity.id === this.e.selected.target || entity.id === this.e.hovered?.id)').replace('if (entity.hp < max || hero)','if (entity.hp < max || hero || entity.id===this.e.hovered?.id)').replace('p.y - 68','p.y - 83').replace('this.overlay.lineStyle(1, 0xddcfac, 0.3);\n      this.overlay.lineBetween(p.x, p.y - 14, p.x, p.y - 34);','if(drop.kind==="jewel" || (drop.item?.rarity??0)>=2){this.overlay.lineStyle(1, 0xddcfac, 0.3);this.overlay.lineBetween(p.x,p.y-14,p.x,p.y-34);}')
.replace('< 9,','< (this.e.showLootLabels?24:7),').replace('.slice(0, 5)', '.slice(0, this.e.showLootLabels?20:4)').replace('fontSize: "11px"','fontSize: "12px"'));
edit('src/core/Engine.ts',s=>s.replace('this.meta[drop.kind] += drop.amount;','this.bus.emit("audio","coin");\n          this.meta[drop.kind] += drop.amount;').replace('if (drop.item) this.run.inventory.push(drop.item);','if (drop.item) this.run.inventory.push(drop.item);\n          this.bus.emit("audio","pickup");').replace('if (drop.jewel) this.run.jewels.push(drop.jewel);','if (drop.jewel) this.run.jewels.push(drop.jewel);\n          this.bus.emit("audio","pickup");').replace('this.bus.emit("notice", "Achado recolhido • I para inventário");','if(!this.meta.tutorials.inventory&&this.run.inventory.length)this.bus.emit("notice", "Um achado na mochila · I para examinar");'));
