import fs from 'node:fs';const edit=(p,f)=>fs.writeFileSync(p,f(fs.readFileSync(p,'utf8')));
edit('src/rendering/Textures.ts',s=>s.replace('import Phaser from "phaser";','import Phaser from "phaser";\nimport {createFoliage} from "./Foliage";').replace('export function createTextures(scene: Phaser.Scene) {','export function createTextures(scene: Phaser.Scene) {\n  createFoliage(scene);'));
edit('src/rendering/EntityRenderer.ts',s=>s.replace('sprite.setTintFill(0xe5e2bc)','sprite.setTint(0xffffff)'));
edit('src/rendering/WorldRenderer.ts',s=>s.replace('import Phaser from "phaser";','import Phaser from "phaser";\nimport {patchNoise,composition} from "../world/generation/Composition";')
.replace('private textures =','private crowns=new Map<string,Array<{image:Phaser.GameObjects.Image;x:number;y:number}>>();\n  private textures =')
.replace('const center = chunkAt(this.e.selected.x, this.e.selected.y);','const center = chunkAt(this.e.selected.x, this.e.selected.y);\n    const subjects=[this.e.selected,...[...this.e.enemies.values()].filter(e=>e.id===this.e.hovered?.id||e.id===this.e.selected.target)].map(worldToIso);\n    for(const list of this.crowns.values())for(const crown of list){const hidden=subjects.some(p=>p.y<crown.y+8&&p.y>crown.y-110&&Math.abs(p.x-crown.x)<51&&p.y-35<crown.y-30);crown.image.alpha=Phaser.Math.Linear(crown.image.alpha,hidden?.25:1,.16)}')
.replace('const objects: Phaser.GameObjects.GameObject[] = [];','const objects: Phaser.GameObjects.GameObject[] = [];\n      const crowns:Array<{image:Phaser.GameObjects.Image;x:number;y:number}>=[];this.crowns.set(key,crowns);')
.replace('const obj = this.scene.add','if(tex.startsWith("tree")||tex==="pine"){const v=tex==="pine"?3:Math.abs((t.x*7+t.y*11)%6),scale=.8+(Math.abs(t.x+t.y)%3)*.09;const trunk=this.scene.add.image(p.x,p.y+22,"trunk"+v).setOrigin(.5,.9).setDepth(p.y+22).setScale(scale),crown=this.scene.add.image(p.x,p.y+22,"crown"+v).setOrigin(.5,.9).setDepth(p.y+23).setScale(scale);objects.push(trunk,crown);crowns.push({image:crown,x:p.x,y:p.y+22});continue}\n          const obj = this.scene.add')
.replace('color.brighten(t.variant * 0.7);','color.brighten(patchNoise(this.e.run.seed+":ground",t.x,t.y,12)*4);')
.replace('ctx.fill();\n        if (t.decor','ctx.fill();ctx.strokeStyle=ctx.fillStyle;ctx.lineWidth=1.1;ctx.stroke();\n        if((this.e.run.worldVersion??1)>=2&&composition(this.e.run.seed,t.x,t.y).trail){ctx.fillStyle="#b3aa7440";ctx.beginPath();ctx.ellipse(x,y+16,30,14,0,0,7);ctx.fill()}\n        if (t.decor')
.replace('"⚑  VIAJANTES"','"Viajantes"').replace('"✧  SANTUÁRIO"','"Santuário"').replace('"◇  ACHADO"','"Achado"').replace('"⌂  " + p.kind.toUpperCase()','p.kind')
.replace('fontSize: "11px"','fontSize: "12px"').replace('this.chunks.delete(key);','this.chunks.delete(key);this.crowns.delete(key);').replace('this.chunks.clear();','this.chunks.clear();this.crowns.clear();'));
